export const FETCH_CURRENCIES_STARTED = "FETCH_CURRENCIES_STARTED";
export const FETCH_CURRENCIES_SUCCESS = "FETCH_CURRENCIES_SUCCESS";
export const FETCH_CURRENCIES_FAILURE = "FETCH_CURRENCIES_FAILURE";

export const UPDATE_VALUES = "UPDATE_VALUES";
export const CALCULATE = "CALCULATE";
